const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const S=require('../assets/stats.js');
const load=p=>JSON.parse(fs.readFileSync(__dirname+'/../data/'+p,'utf8'));const history=load('history.json'),current=load('season-2026.json'),games=S.archive(current,history);
test('Every current lineup reconciles, standings agree with matches',()=>{for(const t of current.currentStandings){let pf=0,w=0,l=0;for(const m of current.matchups){if(![m.a.id,m.b.id].includes(t.id))continue;const me=m.a.id===t.id?m.a:m.b,other=m.a.id===t.id?m.b:m.a;assert.equal(S.round(me.starters.reduce((a,p)=>a+p[2],0)),me.score);pf+=me.score;w+=me.score>other.score;l+=me.score<other.score;}assert.equal(S.round(pf),t.pf);assert.equal(`${w}–${l}`,t.wl);}});
test('Archive includes 295 regular games and 23 actual postseason games; byes excluded',()=>{assert.equal(games.length,318);assert.equal(games.filter(g=>g.phase==='regular').length,295);});
test('All H2H records mirror wins, losses and points in both directions',()=>{for(let a=1;a<=10;a++)for(let b=a+1;b<=10;b++){const x=S.h2h(games,a,b),y=S.h2h(games,b,a);assert.equal(x.wins,y.losses);assert.equal(x.losses,y.wins);assert.equal(x.pf,y.pa);assert.equal(x.pa,y.pf);}assert.equal(S.h2h(games.filter(g=>g.year===2026),6,3,'regular').wins,1);assert.equal(S.h2h(games,6,8,'playoffs').losses,2);});
test('Tie credit and unplayed pairs differ from losses',()=>{const x=S.h2h([{year:2026,week:1,phase:'regular',a:{id:1,score:100},b:{id:2,score:100}}],1,2);assert.equal(x.ties,1);assert.equal(x.pct,50);assert.equal(S.h2h([],1,2).pct,null);});
test('Bracket first round is ordered by the semifinal participants who advance',()=>{for(const p of Object.values(history.playoffs)){const first=S.orderedFirstRound(p);assert.equal(first.length,4);p.r2.forEach((g,i)=>assert.deepEqual(new Set(first.slice(i*2,i*2+2).map(x=>x.bye?x.a[0]:x.winner)),new Set([g.a[0],g.b[0]])));}});
test('Draft awards weight early lost value and expose injury games, incomplete inputs stay pending',()=>{assert.deepEqual(S.draftAwards({}),[]);const input={draftComplete:true,productionComplete:true,draft:[{playerId:'a',position:'RB',overallPick:1,managerId:1},{playerId:'b',position:'RB',overallPick:12,managerId:2}],players:[{playerId:'a',position:'RB',points:10,missedGames:5},{playerId:'b',position:'RB',points:100},{playerId:'c',position:'RB',points:200}]};const r=S.draftAwards(input);assert.equal(r[0].playerId,'a');assert.equal(r[0].bustScore,190);assert.equal(r[0].missedGames,5);assert.equal(r[0].finish,3);});
test('Waiver award excludes pre-acquisition, bench, post-drop and trade-acquired points; deduplicates stints',()=>{assert.deepEqual(S.waiverAwards({}),[]);const input={transactionsComplete:true,lineupsComplete:true,acquisitions:[{managerId:1,playerId:'a',type:'waiver',startWeek:2,endWeek:4},{managerId:1,playerId:'a',type:'free-agent',startWeek:3,endWeek:4},{managerId:1,playerId:'b',type:'trade',startWeek:1}],lineups:[{managerId:1,playerId:'a',week:1,points:100,started:true},{managerId:1,playerId:'a',week:2,points:40,started:false},{managerId:1,playerId:'a',week:3,points:20,started:true},{managerId:1,playerId:'a',week:4,points:90,started:true},{managerId:1,playerId:'b',week:3,points:80,started:true}]};const r=S.waiverAwards(input);assert.equal(r.length,1);assert.equal(r[0].points,20);assert.equal(r[0].starts,1);});

test("Imported history reconciles each manager’s 56-week record",()=>{for(const t of load("managers.json").teams){const rows=games.filter(g=>g.year<=2025&&g.phase==="regular"&&[g.a.id,g.b.id].includes(t.id));const wins=rows.filter(g=>(g.a.id===t.id?g.a.score:g.b.score)>(g.a.id===t.id?g.b.score:g.a.score)).length;assert.equal(rows.length,56);assert.equal(`${wins}–${56-wins}`,t.record);}});
